# Generated by Django 5.2.10 on 2026-01-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VegetablePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vegetable_name", models.CharField(max_length=100)),
                ("market_name", models.CharField(max_length=100)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("avg_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField()),
                ("crawl_time", models.DateTimeField()),
                ("province_code", models.CharField(max_length=20)),
                ("province_name", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=20)),
            ],
        ),
    ]
