# Generated by Django 5.2.9 on 2026-02-22 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vegetableprice", options={"managed": False},
        ),
        migrations.CreateModel(
            name="PredictResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vegetable_name", models.CharField(db_index=True, max_length=50)),
                ("predict_days", models.PositiveIntegerField(default=7)),
                (
                    "model_name",
                    models.CharField(db_index=True, default="top3", max_length=50),
                ),
                (
                    "model_version",
                    models.CharField(db_index=True, default="v1", max_length=50),
                ),
                ("predict_start_date", models.DateField(blank=True, null=True)),
                ("result_json", models.JSONField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predict_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(
                        fields=[
                            "vegetable_name",
                            "predict_days",
                            "model_name",
                            "model_version",
                        ],
                        name="api_predict_vegetab_03efd6_idx",
                    ),
                    models.Index(
                        fields=["created_time"], name="api_predict_created_af4359_idx"
                    ),
                ],
            },
        ),
    ]
